FROM golang:1.20-alpine as builder
ADD . /app/
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o iTaskDemo .

FROM alpine
WORKDIR /app/
COPY --from=builder /app/iTaskDemo .
#EXPOSE
ENTRYPOINT ["/app/iTaskDemo"]

#docker build -t social-todo-service:1.0 .

#MYSQL_GORM_DB_SOURCE=root:my-secret-pw@tcp(127.0.0.1:3309)/social-todo-list?charset=utf8mb4&parseTime=True&loc=Local;
#MYSQL_GORM_DB_SOURCE=root:my-secret-pw@tcp(my_mysql:3306)/social-todo-list?charset=utf8mb4&parseTime=True&loc=Local;
#MYSQL_GORM_DB_TYPE=mysql;SECRET=iTaskSecret2024;SIMPLE_VALUEF=iTask