app:
  Version: 1.0.0
  Port: 8080
  Mode: development
  Secret: 109339Lam
  MigrationURL:  file://migrations

mysql:
  #Host: paradise-mysql
  # Host: localhost
  # ContainerName: paradise_mysql
  # Port: 3306
  # User: root
  # Password: 109339Lam@
  # DBName: paradise
  # Host: roundhouse.proxy.rlwy.net
  # Port: 30663
  # User: root
  # Password: aaCfeH12efF2-3Gfh-b6A--Aac1HH-4c
  # DBName: railway
  Host: khanhtran-rds.c9seqcum6oc9.ap-southeast-1.rds.amazonaws.com
  Port: 3306
  User: root
  Password: Trankhanh47
  DBName: iTask

aws:
  Region: ap-southeast-1
  APIKey: AKIAZQ3DTRXKD62FEZCQ
  SecretKey: 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
  S3Domain: d3prono6kmsi71.cloudfront.net
  S3Bucket: itask
  S3FolderImages: images
#

redis:
  Host: monorail.proxy.rlwy.net
  #Host: localhost
  Port: 33723
  #Port: 6379
  Password: Ld43kK5joKE6DJ1fjOEmkhhncNHe261j
  #Password: ""
  DB: 0

google:
  ClientID: 701762046284-1o7u891fgp06kvi0f7344dikclpmjdmq.apps.googleusercontent.com
  ClientSecret: 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
  RedirectURL: http://localhost:3000/

email:
  EmailSenderName: LamNguyen
  EmailSenderAddress: lamfan011@gmail.com
  EmailSenderPassword: earzqfmxxcxorlxz

cronspec:
  UpdateStatusBooking: 0 0 * * *

googlemap:
  APIKey: AIzaSyA6_RpKmlsfdOrT2mfJ-nbpEO0jgSj_m38
  BaseURL: https://maps.googleapis.com/maps/api/geocode

momo:
  EndPoint: https://test-payment.momo.vn/v2/gateway/api/create
  AccessKey: F8BBA842ECF85
  SecretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  PartnerCode: MOMO
  RedirectURL: https://payment-success-minhtuongle.vercel.app/
  IpURL: https://webhook.site/b3088a6a-2d17-4f8d-a383-71389a6c600b
  Lang: vi
  PartnerName: MoMo Payment
  StoreId: 109339ParadiseBooking
  AutoCapture: true
  RequestType: payWithMethod
