name: Go

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

  #      - name: Build
  #        run: go build -v ./...

#      - name: Test
#        run: go test -v ./...

      - name: Login to AWS ECR
        env:
          ECR_URI: 654654541268.dkr.ecr.ap-southeast-1.amazonaws.com
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region  ${{ secrets.AWS_REGION }}
          aws configure set default.output json
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_URI

      - name: Build and push Docker image
        env:
          ECR_URI: 654654541268.dkr.ecr.ap-southeast-1.amazonaws.com
        run: |
          docker build -t itask .
          docker tag itask:latest $ECR_URI/itask:latest
          docker push $ECR_URI/itask:latest

      - name: Deploy to Server EC2
        uses: appleboy/ssh-action@master
        with:
          env:
            ECR_URI: 654654541268.dkr.ecr.ap-southeast-1.amazonaws.com
          host: ec2-54-169-214-21.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region  ${{ secrets.AWS_REGION }}
            aws configure set default.output json
            aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_URI
            sudo docker login -u AWS -p $(aws ecr get-login-password --region ap-southeast-1) https://$ECR_URI
            sudo docker rm -vf $(docker ps -aq)
            sudo docker rmi -f $(docker images -aq)
            sudo docker run --name AppBE -d -p 8080:8080 $ECR_URI/itask:latest